---
version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: install
          command: 'yarn'
      - run:
          name: build
          command: 'yarn build'
      - run:
          name: release
          command: 'yarn semantic-release || true'
workflows:
  version: 2
  my-workflow:
    jobs:
      - build:
          context: gh-npm-public